### ISSUE TITLE
entrevista_abigail coronel

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-jamm#5]
[ENTREVISTA DE LA WEB 3.0.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-equipo-jamm/files/12542007/ENTREVISTA.DE.LA.WEB.3.0.pdf)

**Comment by DiegoSCP117** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
